[package]
name = "vodb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
bincode = "1.3.3"
lru = "0.12.5"
serde_json = "1.0"
actix-web = "4.0"
tokio = "1.41.0"
clap = "4.5.20"
dotenv = "0.15.0"